default_settings:
  trainer_type: ppo
  hyperparameters:
    batch_size: 2048
    buffer_size: 10240
    learning_rate: 2.0e-05
    learning_rate_schedule: linear
    beta: 0.0005
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 2
  network_settings:
    vis_encode_type: simple
    normalize: false
    hidden_units: 128
    num_layers: 3
    memory:
      sequence_length: 64
      memory_size: 256
  reward_signals:
    extrinsic:
      strength: 1.0
      gamma: 0.99
  max_steps: 9999999999999999
  time_horizon: 64
  summary_freq: 1000
